["字"]
"德"="悳"
"陕"="陝"
"盗"="盜"
"羡"="羨"
"抑"="𢬃"
"肥"="⿰月𭅲"
"圣"="聖"
"苏"="⿱艹稣"
"思"="恖"
"细"="⿰纟囟"
"闹"="鬧"
"往"="𢓸"
"庙"="庿"
"时"="旹"
"听"="𦔻"
"赵"="趙"
"鸡"="雞"
"毅"="𣫖"

["词"."薑"]
"生姜"="生薑"
"姜黄"="薑黄"

["词"."鬥"]
"斗争"="鬥争"
"战斗"="戰鬥"
"格斗"="挌鬥"

["词"."𳐝"]
"咸菜"="𳐝菜"
"咸肉"="𳐝肉"
"咸水湖"="𳐝水湖"